import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export const FeatureSection = () => {
  return (
    <section className="py-20 px-6">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Explore the Bakugan Gallery
          </h2>
          <p className="text-xl text-muted-foreground">
            See all the amazing Bakugan generated by our community!
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {/* Placeholder for Bakugan images */}
          <Card className="p-4 bg-card border-border flex items-center justify-center h-48">
            <span className="text-muted-foreground">Bakugan Image 1</span>
          </Card>
          <Card className="p-4 bg-card border-border flex items-center justify-center h-48">
            <span className="text-muted-foreground">Bakugan Image 2</span>
          </Card>
          <Card className="p-4 bg-card border-border flex items-center justify-center h-48">
            <span className="text-muted-foreground">Bakugan Image 3</span>
          </Card>
          <Card className="p-4 bg-card border-border flex items-center justify-center h-48">
            <span className="text-muted-foreground">Bakugan Image 4</span>
          </Card>
          <Card className="p-4 bg-card border-border flex items-center justify-center h-48">
            <span className="text-muted-foreground">Bakugan Image 5</span>
          </Card>
          <Card className="p-4 bg-card border-border flex items-center justify-center h-48">
            <span className="text-muted-foreground">Bakugan Image 6</span>
          </Card>
          <Card className="p-4 bg-card border-border flex items-center justify-center h-48">
            <span className="text-muted-foreground">Bakugan Image 7</span>
          </Card>
          <Card className="p-4 bg-card border-border flex items-center justify-center h-48">
            <span className="text-muted-foreground">Bakugan Image 8</span>
          </Card>
        </div>

        <div className="text-center mt-12">
          <Button className="bg-primary text-primary-foreground hover:bg-primary/90 px-8 py-3 text-lg">
            View More
          </Button>
        </div>
      </div>
    </section>
  );
};

